version: '3'
volumes: 
  data: {}
  data2: {}
services:
    minio:
        image: minio/minio:RELEASE.2021-08-25T00-41-18Z.hotfix.25b67de4f
        container_name: minio
        command: [
            gateway,
            gcs,
        ]
        volumes:
            - data:/data
            - $HOME/.config/gcloud/application_default_credentials.json:/credentials/gcs.json
        ports:
          - 9000:9000
        environment:
            MINIO_ROOT_USER: accesskey
            MINIO_ROOT_PASSWORD: secretkey
            GOOGLE_APPLICATION_CREDENTIALS: /credentials/gcs.json
            MINIO_CACHE_DRIVES: /data
            MINIO_CACHE_AFTER: 0
            MINIO_CACHE_WATERMARK_LOW: 75
            MINIO_CACHE_WATERMARK_HIGH: 85
            MINIO_CACHE_QUOTA: 90
    minio2:
        image: minio/minio:RELEASE.2021-08-25T00-41-18Z.hotfix.25b67de4f
        container_name: minio2
        command: [
            gateway,
            gcs,
        ]
        volumes:
            - data:/data
            - $HOME/.config/gcloud/application_default_credentials.json:/credentials/gcs.json
        ports:
          - 9001:9000
        environment:
            MINIO_ROOT_USER: accesskey
            MINIO_ROOT_PASSWORD: secretkey
            GOOGLE_APPLICATION_CREDENTIALS: /credentials/gcs.json
            MINIO_CACHE_DRIVES: /data
            MINIO_CACHE_AFTER: 0
            MINIO_CACHE_WATERMARK_LOW: 75
            MINIO_CACHE_WATERMARK_HIGH: 85
            MINIO_CACHE_QUOTA: 90
